/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ServeursRouteImport } from './routes/serveurs'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as CaisseRouteImport } from './routes/caisse'
import { Route as IndexRouteImport } from './routes/index'

const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeursRoute = ServeursRouteImport.update({
  id: '/serveurs',
  path: '/serveurs',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const CaisseRoute = CaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/journal': typeof JournalRoute
  '/serveurs': typeof ServeursRoute
  '/stock': typeof StockRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/journal': typeof JournalRoute
  '/serveurs': typeof ServeursRoute
  '/stock': typeof StockRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/journal': typeof JournalRoute
  '/serveurs': typeof ServeursRoute
  '/stock': typeof StockRoute
  '/ventes': typeof VentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caisse' | '/journal' | '/serveurs' | '/stock' | '/ventes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/caisse' | '/journal' | '/serveurs' | '/stock' | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/caisse'
    | '/journal'
    | '/serveurs'
    | '/stock'
    | '/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaisseRoute: typeof CaisseRoute
  JournalRoute: typeof JournalRoute
  ServeursRoute: typeof ServeursRoute
  StockRoute: typeof StockRoute
  VentesRoute: typeof VentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serveurs': {
      id: '/serveurs'
      path: '/serveurs'
      fullPath: '/serveurs'
      preLoaderRoute: typeof ServeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caisse': {
      id: '/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof CaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaisseRoute: CaisseRoute,
  JournalRoute: JournalRoute,
  ServeursRoute: ServeursRoute,
  StockRoute: StockRoute,
  VentesRoute: VentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
