/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as IndexRouteImport } from './routes/index'

const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ventes': typeof VentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ventes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ventes'
  id: '__root__' | '/' | '/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VentesRoute: typeof VentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VentesRoute: VentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
